import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Bell,
  BellOff,
  Bookmark,
  Briefcase,
  Building2,
  Calendar,
  CalendarCheck2,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  CalendarX,
  Camera,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Circle,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Download,
  Eye,
  FileCheck2,
  FilePlus,
  FileText,
  FileWarning,
  Flag,
  FlaskConical,
  Gavel,
  Globe,
  HelpCircle,
  Home,
  Image as ImageIcon,
  Inbox,
  Info,
  LayoutDashboard,
  LifeBuoy,
  LogIn,
  LogOut,
  type LucideIcon,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  MessageSquare,
  MessageSquareWarning,
  MoreVertical,
  PanelLeftOpen,
  Phone,
  Plus,
  Receipt,
  Reply,
  RotateCcw,
  Search,
  Send,
  Settings,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Tag,
  Tags,
  Target,
  Timer,
  ToggleRight,
  Trash2,
  TrendingUp,
  Truck,
  Upload,
  UploadCloud,
  User,
  UserCheck,
  UserCog,
  UserPlus,
  Wrench,
  X,
} from "lucide-react";

/**
 * Curated icon registry. Adding a new icon requires both an import above and a
 * map entry below, which keeps <Icon name="..."> type-safe end-to-end and lets
 * bundlers tree-shake only the icons actually used.
 */
export const ICONS = {
  activity: Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "badge-check": BadgeCheck,
  bell: Bell,
  "bell-off": BellOff,
  bookmark: Bookmark,
  briefcase: Briefcase,
  "building-2": Building2,
  calendar: Calendar,
  "calendar-check-2": CalendarCheck2,
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  "calendar-plus": CalendarPlus,
  "calendar-x": CalendarX,
  camera: Camera,
  check: Check,
  "check-check": CheckCheck,
  "check-circle-2": CheckCircle2,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevrons-up-down": ChevronsUpDown,
  circle: Circle,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock,
  download: Download,
  eye: Eye,
  "file-check-2": FileCheck2,
  "file-plus": FilePlus,
  "file-text": FileText,
  "file-warning": FileWarning,
  flag: Flag,
  "flask-conical": FlaskConical,
  gavel: Gavel,
  globe: Globe,
  "help-circle": HelpCircle,
  home: Home,
  image: ImageIcon,
  inbox: Inbox,
  info: Info,
  "layout-dashboard": LayoutDashboard,
  "life-buoy": LifeBuoy,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "message-square-warning": MessageSquareWarning,
  "more-vertical": MoreVertical,
  "panel-left-open": PanelLeftOpen,
  phone: Phone,
  plus: Plus,
  receipt: Receipt,
  reply: Reply,
  "rotate-ccw": RotateCcw,
  search: Search,
  send: Send,
  settings: Settings,
  "settings-2": Settings2,
  "shield-check": ShieldCheck,
  "sliders-horizontal": SlidersHorizontal,
  sparkles: Sparkles,
  star: Star,
  stethoscope: Stethoscope,
  store: Store,
  tag: Tag,
  tags: Tags,
  target: Target,
  timer: Timer,
  "toggle-right": ToggleRight,
  "trash-2": Trash2,
  "trending-up": TrendingUp,
  truck: Truck,
  upload: Upload,
  "upload-cloud": UploadCloud,
  user: User,
  "user-check": UserCheck,
  "user-cog": UserCog,
  "user-plus": UserPlus,
  wrench: Wrench,
  x: X,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
